### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by backkem** [pions/website#7]
Maybe I'm missing something but if I try to build from master it is complaining the following files are missing:
- `script.html` & `google-analytics-async.html` in  `layouts/_default/baseof.html`
- `style.html` in `layouts/partials/head.html`
- `date-and-tags.html` in  `layouts/_default/list.html` (when adding content)

**Comment by Sean-Der** [comment]
@backkem what version of hugo? I am not seeing these errors on `travis` but I might only be building a subset? https://travis-ci.org/pions/website/builds/500463482

Also hopefully we don't have GA enabled! I think I removed everything, but I definitely don't want to be tracking users.

**Comment by backkem** [comment]
Thanks latest (0.54 extended) maybe the problem only occurs on Windows, idk. I can build if I remove the references to those files mentioned. I'll just do that locally for now.

**Comment by backkem** [comment]
Forgot about the sub-modules 🤦‍♂️.
