### ISSUE TITLE
Menu becomes invisible/unreadable

### ISSUE THREAD

**Issue by backkem** [pions/website#8]
The main menu becomes unreadable when:
- Scroling down on the main page since it adds a white toolbar:
![image](https://user-images.githubusercontent.com/38858977/53636159-871d2e00-3c1f-11e9-99b8-cd255cafd4fb.png)
- Visiting any other page since it no longer has the red background:
![image](https://user-images.githubusercontent.com/38858977/53636196-9ef4b200-3c1f-11e9-8ee5-00f60b65eaf6.png)
- Hovering over it with the red background:
![image](https://user-images.githubusercontent.com/38858977/53636112-61902480-3c1f-11e9-8cf6-3f39bfaabf5c.png)

**Comment by backkem** [comment]
This is relevant again with the new design.

**Comment by Sean-Der** [comment]
Fixed again!
